stages:
  - test
  - build
  - release
  - deploy

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
# NOTE: For semantic-release node should be >= 8.3
image: node:8

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

lint app:
  stage: test
  script:
    - yarn install --no-progress
    - yarn lint
  only:
    - master

test unit:
  stage: test
  script:
    - yarn install --no-progress
    - yarn test:unit
  only:
    - master

build app:
  stage: build
  script:
    - yarn install --no-progress
    - yarn build
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    expire_in: 1 week
    paths:
      - dist
  only:
    - master

release:
  stage: release
  script:
    - yarn semantic-release

# Pipelines starting with `.` - skipped.
# TODO: implement
.deploy:
  stage: deploy
